[package]
name = "slam_test"
version = "0.1.0"
edition = "2024"

[package.metadata.pepsi]
cross-compile = true

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
coordinate_systems = { workspace = true }
eframe = { workspace = true }
egui_plot = { workspace = true }
image = { workspace = true, features = ["png"] }
linear_algebra = { workspace = true }
ndarray = { workspace = true }
visual_odometry_rust = { workspace = true }
indicatif = { workspace = true }
