[package]
name = "slam_frontend"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
ball-tree = { workspace = true }
color-eyre = { workspace = true }
hnsw_rs = { workspace = true }
nalgebra = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
