[package]
name = "dds"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
booster_low_level_interface = { version = "0.1.0", path = "../booster_low_level_interface" }
color-eyre.workspace = true
futures = "0.3.31"
rustdds.workspace = true
tokio = { workspace = true, features = ["sync"] }
