[package]
name = "visual_odometry"
version = "0.1.0"
edition = "2024"

[dependencies]
coordinate_systems = { workspace = true }
linear_algebra = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5" }
image = { workspace = true, features = ["png"] }

[[bench]]
name = "fps"
harness = false
