[package]
name = "localization-factrs"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre.workspace = true
context_attribute.workspace = true
framework.workspace = true
hardware.workspace = true
ros2.workspace = true
serde.workspace = true
types.workspace = true
booster.workspace = true
factrs = { git = "https://github.com/oleflb/fact-rs.git", rev = "be79625b0a7eef228aafa8ff78d16022d77389c1"}
nalgebra.workspace = true
faer = "0.24.0"
linear_algebra.workspace = true
tokio.workspace = true
thiserror.workspace = true
log.workspace = true
