[package]
name = "slam"
version = "0.1.0"
edition = "2024"

[dependencies]
apex-solver = { workspace = true }
color-eyre = { workspace = true }
coordinate_systems = { workspace = true }
csv = "1.1"
indicatif = { workspace = true }
kdtree = "0.7.0"
linear_algebra = { workspace = true }
nalgebra = { workspace = true }
ndarray = { workspace = true }
ordered-float = { workspace = true }
ort = { workspace = true }
pyo3 = { workspace = true, features = ["auto-initialize", "abi3-py314"]}
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
image = { workspace = true, features = ["png"] }
eframe = { workspace = true }
numpy = "0.27.0"
egui_plot = { workspace = true }
