[package]
name = "slam"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = { workspace = true }
coordinate_systems = { workspace = true }

indicatif = { workspace = true }
linear_algebra = { workspace = true }
nalgebra = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = "1.1"
apex-solver = { workspace = true }
kdtree = "0.7.0"
ndarray = { workspace = true }
ort = { workspace = true }
